version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/  # Temporary location to store the build file before extraction

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
