version: 0.0
os: linux
files:
  - source: s3://dreams-staging-backet/frontendcode/build.zip
    destination: /home/ubuntu/frontend_build.zip  # Temporary location to store the build file before extraction

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
